services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - AUTH_API_URL=http://auth-api:8081
      - TODOS_API_URL=http://todos-api:8082
    depends_on:
      - auth-api
      - todos-api

  auth-api:
    build: ./auth-api
    ports:
      - "8081:8081"
    environment:
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=myfancysecret
      - AUTH0_DOMAIN=dev-tid73ii8jxvdvwqs.us.auth0.com
      - AUTH0_CLIENT_ID=mo5ymMcSCCTv5T5ierrnuNVpTkZ1M4z5
      - AUTH0_CLIENT_SECRET=7zWZDWBiJms-EJHj-a6AM10N_l06AQvxH_l6hhRZVos9YWc-s2VCuUlUtBDukM94
    depends_on:
      - users-api

  users-api:
    build:
      context: ./users-api
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=myfancysecret
    command: ["java", "-jar", "app.jar", "--server.port=8083"]

  todos-api:
    build: ./todos-api
    ports:
      - "8082:8082"
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=myfancysecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  log-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge