name: Log Message Processor CI/CD

on:
  push:
    branches: [ main, infra-develop ]
    paths:
      - 'log-message-processor/**'
      - '.github/workflows/log-processor-ci.yml'

env:
  SERVICE_NAME: log-processor
  ACR_NAME: microserviceappdevacr
  RESOURCE_GROUP: microservice-app-dev-rg
  IMAGE_TAG: v1.0.${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image to ACR
      uses: docker/build-push-action@v4
      with:
        context: ./log-message-processor
        file: ./log-message-processor/Dockerfile
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME }}:latest

    - name: Update App Service
      run: |
        az webapp config container set \
          --name microservice-app-dev-${{ env.SERVICE_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }} \
          --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

    # Note: No health check for log processor as it's a background service